<?php

function ky100_block_info() {
    $blocks['term_parent'] = array(
        'info' => t('Родительская категория'),
    );
    return $blocks;
}

function ky100_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'term_parent':
            $block['subject'] = t('Родительская категория');
            $block['content'] = get_term();
            break;
    }
    return $block;
}


function get_term(){
    $tid = arg(2);
    $term = taxonomy_term_load($tid);
    if(!empty($term->field_term_image)){
        return theme('term', array('name' => $term->name, 'image' => $term->field_term_image));
    } else{
        return theme('term', array('name' => $term->name));
    }

}

function ky100_theme() {
    $module_path = drupal_get_path('module', 'ky100');
    return array(
        'term' => array(
            'template' => 'term',
            'path' => $module_path,
        )
    );
}