<?php

function ky100_block_info() {
    $blocks['term_parent'] = array(
        'info' => t('Родительская категория'),
    );
    return $blocks;
}

function ky100_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'term_parent':
            $block['subject'] = t('Родительская категория');
            $block['content'] = get_term();
            break;
    }
    return $block;
}


function get_term(){
    $tid = arg(2);
    $term = taxonomy_term_load($tid);
    if(!empty($term->field_term_image)){
        return theme('term', array('name' => $term->name, 'image' => $term->field_term_image));
    } else{
        return theme('term', array('name' => $term->name));
    }

}

function ky100_theme() {
    $module_path = drupal_get_path('module', 'ky100');
    return array(
        'term' => array(
            'template' => 'term',
            'path' => $module_path,
        )
    );
}

function ky100_form_alter(&$form, $form_state, $form_id)  {
    global $user;
    if ($form_id == 'user_profile_form'){
        unset($form['field_pravila']);
        unset($form['field_dannie']);
        unset($form['field_mess_conf']);
        if($user->uid == 1){
            $form['new_message'] = array (
                '#markup' => l(t('Write new message'), 'messages/new'),
                '#weight' => -2,
                '#prefix' => '<div>',
                '#suffix' => '</div>'
            );
        }
    }
    if($form_id == 'catalog_form_form'){
        $form['refresh'] = array(
            '#markup' => l('', 'captcha/refresh/catalog_form_form', array('attributes' => array('id' =>'reload-captcha', 'class' => 'p'))),
            '#weight' => 1,
        );
    }
}